[package]
name = "echor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.39"

[dev-dependencies]
anyhow = "1.0.98"
assert_cmd = "2.0.17"
predicates = "3.1.3"
pretty_assertions = "1.4.1"
